project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  #site-url: "https://www.dylanbretzjr.com"
  title: "Dylan Bretz Jr."
  description: "Dylan Bretz Jr. is a musician and growing data professional dedicated to critical thinking and lifelong learning."
  favicon: /img/logo.svg
  image: /img/portrait.jpg
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: https://docs.google.com/document/d/e/2PACX-1vRAPxM0I4u_5OEYcn9zzhkxiM-7RCJyFQUNOlqXw0qTFCNofu5yxJ2OIq2L44krB5LJjqXgAu4_gFSX/pub
        text: Resume
      - href: contact.qmd
        text: Contact
    right:
      - icon: linkedin
        url: https://www.linkedin.com/in/dylan-bretz-b74311153/
      - icon: github
        url: https://github.com/dylanbretzjr
      - text: "{{< fa envelope >}}"
        url: mailto:dylanbretzjr@gmail.com
  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org) and [<i class="bi bi-github"></i> GitHub Pages](https://docs.github.com/en/pages).
    center: |
      Copyright Â© 2026 Dylan Bretz Jr.
  twitter-card: true
  open-graph: true
  back-to-top-navigation: true
  #repo-url: https://github.com/dylanbretzjr/dylanbretzjr.github.io
  #repo-actions: [edit, source, issue]
  #bread-crumbs: true

format:
  html:
    date-format: "YYYY-MM-DD"
    lang: en-US
    respect-user-color-scheme: true
    theme:
      light:
        - cosmo
        - brand
      dark:
        - cosmo
        - brand
    css: styles.css
    fontsize: 20px
    toc: true
    toc-title: "Table of Contents"
    toc-depth: 3
    toc-expand: 3
    fig-align: center
    smooth-scroll: true
    code-overflow: scroll
    grid:
      margin-width: 300px
